name: Bitnodes Bot

on:
  schedule:
    - cron: "*/30 * * * *"   # every 30 minutes (cron uses UTC)
  workflow_dispatch:         # allow manual "Run workflow"

permissions:
  contents: write            # needed to push last_data.json back to repo

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0     # required to push back

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run bot (once)
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python bot_once.py

      - name: Commit & push state file
        if: always()
        run: |
          if [ -f last_data.json ]; then
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git add last_data.json
            git diff --cached --quiet || git commit -m "Update last_data.json [skip ci]"
            git push
          fi
